server.port=8082

spring.datasource.url=jdbc:mysql://test-server:3306/testdb
spring.datasource.username=testuser
spring.datasource.password=testpass

logging.level.root=INFO

message=Testing Environment
